---
openapi: 3.0.0
info:
   version: 1.3.0
   title: testapp open api specification
   description: crudapp API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8125
     description: crudapp
tags:
- name: student
- name: marks
paths:
   "/student/{id}":
      delete:
         tags:
         -  student
         description: GpDelete
         parameters:
         -  in: "path"
            description: GpDelete
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/student":
      put:
         tags:
         -  student
         description: GpUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/student"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  student
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  student
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/student"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/student/userid/created_by":
      get:
         tags:
         -  student
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      student:
         type: object
         properties:
            name:
               type: "string"
               description: Description
            cls:
               type: "string"
               description: Description
            rollno:
               type: "string"
               description: Description
      marks:
         type: object
         properties:
            rollno:
               type: "string"
               description: Description
            tamil:
               type: "string"
               description: Description
            english:
               type: "string"
               description: Description
            maths:
               type: "string"
               description: Description